import { writable } from 'svelte/store';

interface SelectedFeedData {
    id: string;
    title: string;
    tags: string;
    summaryHtmlSnippet: string;
    link: string;
    contentOrigin?: string;
}

interface FeedLabels { // TODO: refactor.....
    [key: string]: string;
}

interface FeedVO {
    labels: FeedLabels;
    time: string; // Comes as string, parse for sorting
    // Add a unique ID property generated by getFeedItemId
    id?: string;
}

interface QueryResponse {
    summary: string;
    feeds: FeedVO[];
    count: number;
}

export const selectedFeedStore = writable<SelectedFeedData | null>(null);

export const queryFeedsStore = writable<QueryResponse | null>(null);
