import { writable } from 'svelte/store';

interface SelectedFeedData {
    id: string;
    title: string;
    tags: string;
    summaryHtmlSnippet: string;
    link: string;
    contentOrigin?: string;
}

interface FeedLabels { // TODO: refactor.....
    [key: string]: string;
}

interface FeedVO {
    labels: FeedLabels;
    time: string; // Comes as string, parse for sorting
    // Add a unique ID property generated by getFeedItemId
    id?: string;
}

export interface QueryRequest {
    start: string;
    end: string;
    limit: number;
    query: string;
    summarize: boolean;
}

interface QueryResponse {
    summary: string;
    feeds: FeedVO[];
    count: number;
    request?: QueryRequest;
}

export const selectedFeedStore = writable<SelectedFeedData | null>(null);

export const queryFeedsStore = writable<QueryResponse | null>(null);
export const lastQueryRequestStore = writable<QueryRequest | null>(null);
